---
- name: redis-cluster-configure | Apply config files /etc/redis/redis.conf
  ansible.builtin.template:
    src: etc/redis/redis.conf.j2
    dest: /etc/redis/redis.conf
    mode: 0644
    owner: redis
    group: redis
  notify: Warning file /etc/redis/redis.conf has been changed

- name: redis-cluster-configure | Ensures redis is started and enabled
  ansible.builtin.systemd:
    name: redis
    daemon_reload: True
    enabled: True
    state: started